### ISSUE TITLE
Feature request, please upgrade PCL to a newer version (1.30)

### ISSUE THREAD

**Issue by zhangzscn** [luigifreda/plvs#9]
I have successfully upgraded the PCL version in PLVS to 1.30, the relevant changes are described in the question #6. Please help to upgrade the PCL version of PLVS, 1.10 is too old.

**Comment by luigifreda** [comment]
Thanks for your feedback. I understand your point. 
Using a local PCL install requires recompiling all the ROS packages that depend on PCL when compiling the ROS workspace (otherwise we get undefined behavior when linking against two versions of the same library). 
I'll do my best to open an option for that.
